/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

/**
 *
 * @author Emilio Jr
 */
public class Interfaz extends javax.swing.JFrame {

        /**
         * Creates new form Interfaz
         */
        public Interfaz() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                entradainput = new javax.swing.JTextField();
                startbutton = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                preordeninput = new javax.swing.JTextArea();
                jScrollPane2 = new javax.swing.JScrollPane();
                inordeninput = new javax.swing.JTextArea();
                jScrollPane3 = new javax.swing.JScrollPane();
                posordeninput = new javax.swing.JTextArea();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));
                getContentPane().add(entradainput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 40));

                startbutton.setText("Evaluar");
                startbutton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                startbuttonActionPerformed(evt);
                        }
                });
                getContentPane().add(startbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

                preordeninput.setColumns(20);
                preordeninput.setRows(5);
                jScrollPane1.setViewportView(preordeninput);

                getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 190, 310));

                inordeninput.setColumns(20);
                inordeninput.setRows(5);
                jScrollPane2.setViewportView(inordeninput);

                getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 210, 310));

                posordeninput.setColumns(20);
                posordeninput.setRows(5);
                jScrollPane3.setViewportView(posordeninput);

                getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 210, 310));

                jLabel1.setText("PreOrden");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

                jLabel2.setText("InOrden");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

                jLabel3.setText("PreOrden");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void startbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbuttonActionPerformed
                // TODO add your handling code here:
                String string=entradainput.getText();
                Tree EBT=new Tree(string);
                preordeninput.setText(EBT.toString(0));
                inordeninput.setText(EBT.toString(1));
                posordeninput.setText(EBT.toString(2));
        }//GEN-LAST:event_startbuttonActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Interfaz().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField entradainput;
        private javax.swing.JTextArea inordeninput;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTextArea posordeninput;
        private javax.swing.JTextArea preordeninput;
        private javax.swing.JButton startbutton;
        // End of variables declaration//GEN-END:variables
}
